### ISSUE TITLE
github workflow license_finder failed.

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/terraform-controller#8]
```
Run license_finder --decisions_file .license/dependency_decisions.yml
  license_finder --decisions_file .license/dependency_decisions.yml
  shell: /usr/bin/bash -e {0}
LicenseFinder::GoModules: is active
/opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/package_managers/go_modules.rb:61:in `block in packages_info': Command 'GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...' failed to execute (RuntimeError)
GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...: did not succeed.
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/package_managers/go_modules.rb:32:in `chdir'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/package_managers/go_modules.rb:32:in `packages_info'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/package_managers/go_modules.rb:20:in `current_packages'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/package_manager.rb:105:in `current_packages_with_relations'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/scanner.rb:42:in `each'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/scanner.rb:42:in `flat_map'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/scanner.rb:42:in `active_packages'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/core.rb:83:in `current_packages'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/core.rb:78:in `decision_applier'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/2.7.0/forwardable.rb:229:in `any_packages?'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/license_aggregator.rb:17:in `block in any_packages?'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/license_aggregator.rb:15:in `map'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/license_aggregator.rb:15:in `any_packages?'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/lib/license_finder/cli/main.rb:112:in `action_items'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/lib/ruby/gems/2.7.0/gems/license_finder-6.12.2/bin/license_finder:6:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/bin/license_finder:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.1/x64/bin/license_finder:23:in `<main>'
GO111MODULE=on go list -mod=readonly -deps -f '{{ if and (.DepOnly) (not .Standard) }}{{ $mod := (or .Module.Replace .Module) }}{{ $mod.Path }},{{ $mod.Version }},{{ or $mod.Dir .Dir }}{{ end }}' ./...: Getting the dependencies from go list failed 
	go: downloading k8s.io/apimachinery v0.18.8
go: downloading sigs.k8s.io/controller-runtime v0.6.2
go: downloading k8s.io/api v0.18.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/go-logr/logr v0.4.0
go: downloading k8s.io/utils v0.0.0-20200603063816-c1c6865ac451
go: downloading k8s.io/client-go v0.18.8
go: downloading go.uber.org/zap v1.10.0
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading k8s.io/klog/v2 v2.4.0
go: downloading github.com/google/gofuzz v1.1.0
go: downloading github.com/evanphx/json-patch v4.5.0+incompatible
go: downloading github.com/spf13/pflag v1.0.5
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading go.uber.org/multierr v1.1.0
go: downloading github.com/ghodss/yaml v1.0.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/json-iterator/go v1.1.10
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/go-logr/zapr v0.4.0
go: downloading golang.org/x/net v0.0.0-20201006153459-a7d1128ccaa0
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading gomodules.xyz/jsonpatch/v2 v2.0.1
go: downloading github.com/googleapis/gnostic v0.3.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading go.uber.org/atomic v1.4.0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading cloud.google.com/go v0.45.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading k8s.io/apiextensions-apiserver v0.18.6
go: downloading github.com/google/go-cmp v0.4.0
go: downloading google.golang.org/protobuf v1.23.0
go: downloading sigs.k8s.io/structured-merge-diff/v3 v3.0.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/imdario/mergo v0.3.9
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/prometheus/common v0.4.1
go: downloading github.com/prometheus/procfs v0.0.11
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/golang/groupcache v0.0.0-20190129154638-5b532d6fd5ef
go: downloading golang.org/x/sys v0.0.0-20210320140829-1e4c9ba3b0c4
go: downloading k8s.io/kube-openapi v0.0.0-20200410145947-bcb3869e6f29
go: updates to go.sum needed, disabled by -mod=readonly

Error: Process completed with exit code 1.
```

While when running locally, it succeeded.

```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/oam-dev/terraform-controller git:(clean-go-mod) ✗ license_finder --decisions_file .license/dependency_decisions.yml
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring sassc-2.4.0 because its extensions are not built. Try: gem pristine sassc --version 2.4.0
LicenseFinder::GoModules: is active

All dependencies are approved for use
```

**Comment by zzxwill** [comment]
By cleaning go mod cache, it fixed.
